// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/chat": {
    params: {};
  };
  "/generate": {
    params: {};
  };
  "/image": {
    params: {};
  };
  "/recipes": {
    params: {};
  };
  "/recipes/:recipeId": {
    params: {
      "recipeId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/chat" | "/generate" | "/image" | "/recipes" | "/recipes/:recipeId";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "components/Layout.tsx": {
    id: "components/Layout";
    page: "/chat" | "/generate" | "/image" | "/recipes" | "/recipes/:recipeId";
  };
  "routes/chat.tsx": {
    id: "routes/chat";
    page: "/chat";
  };
  "routes/generate.tsx": {
    id: "routes/generate";
    page: "/generate";
  };
  "routes/image.tsx": {
    id: "routes/image";
    page: "/image";
  };
  "routes/recipes.tsx": {
    id: "routes/recipes";
    page: "/recipes";
  };
  "routes/recipe.$recipeId.tsx": {
    id: "routes/recipe.$recipeId";
    page: "/recipes/:recipeId";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "components/Layout": typeof import("./app/components/Layout.tsx");
  "routes/chat": typeof import("./app/routes/chat.tsx");
  "routes/generate": typeof import("./app/routes/generate.tsx");
  "routes/image": typeof import("./app/routes/image.tsx");
  "routes/recipes": typeof import("./app/routes/recipes.tsx");
  "routes/recipe.$recipeId": typeof import("./app/routes/recipe.$recipeId.tsx");
};